/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author raxielh
 */
public class PrincipalJFrame extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalJFrame
     */
    public PrincipalJFrame() {
        initComponents();
        setLocationRelativeTo(null);		
        setVisible(true);
        this.setExtendedState(MAXIMIZED_BOTH);
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int height = pantalla.height;
        int width = pantalla.width;
        setSize(width, height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        link_departamentos = new javax.swing.JMenuItem();
        link_municipios = new javax.swing.JMenuItem();
        link_roles = new javax.swing.JMenuItem();
        link_usuarios = new javax.swing.JMenuItem();
        link_tipoinsumos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        Usuario_inicio = new javax.swing.JMenu();
        btn_logout = new javax.swing.JMenuItem();
        btn_exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktop.setMinimumSize(new java.awt.Dimension(900, 600));

        jMenu1.setText("Configuracion");

        link_departamentos.setText("Departamentos");
        link_departamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                link_departamentosActionPerformed(evt);
            }
        });
        jMenu1.add(link_departamentos);

        link_municipios.setText("Municipios");
        link_municipios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                link_municipiosActionPerformed(evt);
            }
        });
        jMenu1.add(link_municipios);

        link_roles.setText("Roles");
        link_roles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                link_rolesActionPerformed(evt);
            }
        });
        jMenu1.add(link_roles);

        link_usuarios.setText("Usuarios");
        link_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                link_usuariosActionPerformed(evt);
            }
        });
        jMenu1.add(link_usuarios);

        link_tipoinsumos.setText("Tipo de Insumos");
        link_tipoinsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                link_tipoinsumosActionPerformed(evt);
            }
        });
        jMenu1.add(link_tipoinsumos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Entradas");

        jMenuItem1.setText("Movimientos");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Reportes");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Salidas");

        jMenuItem3.setText("Movimientos");
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Reportes");
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Devoluciones");

        jMenuItem7.setText("Movimientos");
        jMenu4.add(jMenuItem7);

        jMenuItem8.setText("Reportes");
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Perdidas");

        jMenuItem6.setText("Movimientos");
        jMenu5.add(jMenuItem6);

        jMenuItem5.setText("Reportes");
        jMenu5.add(jMenuItem5);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Inventario");

        jMenuItem9.setText("Ver");
        jMenu6.add(jMenuItem9);

        jMenuItem10.setText("Reportes");
        jMenu6.add(jMenuItem10);

        jMenuBar1.add(jMenu6);

        Usuario_inicio.setText("..");

        btn_logout.setText("Cerrar Sesión");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        Usuario_inicio.add(btn_logout);

        btn_exit.setText("Salir");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        Usuario_inicio.add(btn_exit);

        jMenuBar1.add(Usuario_inicio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void link_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_link_usuariosActionPerformed
        // TODO add your handling code here:
        UsuariosJInternalFrame users_view = new UsuariosJInternalFrame();
        jDesktop.add(users_view);
        Dimension desktopSize = jDesktop.getSize();
        Dimension FrameSize = users_view.getSize();
        users_view.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        users_view.show();
    }//GEN-LAST:event_link_usuariosActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        LoginJFrame login = new LoginJFrame();
        login.setVisible(true);
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void link_rolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_link_rolesActionPerformed
        // TODO add your handling code here:
        RolJInternalFrame rol_view = new RolJInternalFrame();
        jDesktop.add(rol_view);
        Dimension desktopSize = jDesktop.getSize();
        Dimension FrameSize = rol_view.getSize();
        rol_view.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);        
        rol_view.show();
    }//GEN-LAST:event_link_rolesActionPerformed

    private void link_tipoinsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_link_tipoinsumosActionPerformed
        // TODO add your handling code here:
        TipoInsumosJInternalFrame tipoinsumo = new TipoInsumosJInternalFrame();
        jDesktop.add(tipoinsumo);
        Dimension desktopSize = jDesktop.getSize();
        Dimension FrameSize = tipoinsumo.getSize();
        tipoinsumo.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        tipoinsumo.show();
    }//GEN-LAST:event_link_tipoinsumosActionPerformed

    private void link_departamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_link_departamentosActionPerformed
        // TODO add your handling code here:
        DepartamentosJInternalFrame departamentos = new DepartamentosJInternalFrame();
        jDesktop.add(departamentos);
        Dimension desktopSize = jDesktop.getSize();
        Dimension FrameSize = departamentos.getSize();
        departamentos.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);                
        departamentos.show();
    }//GEN-LAST:event_link_departamentosActionPerformed

    private void link_municipiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_link_municipiosActionPerformed
        // TODO add your handling code here:
        MunicipiosJInternalFrame municipios = new MunicipiosJInternalFrame();
        jDesktop.add(municipios);
        Dimension desktopSize = jDesktop.getSize();
        Dimension FrameSize = municipios.getSize();
        municipios.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);                
        municipios.show();
    }//GEN-LAST:event_link_municipiosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenu Usuario_inicio;
    private javax.swing.JMenuItem btn_exit;
    private javax.swing.JMenuItem btn_logout;
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem link_departamentos;
    private javax.swing.JMenuItem link_municipios;
    private javax.swing.JMenuItem link_roles;
    private javax.swing.JMenuItem link_tipoinsumos;
    private javax.swing.JMenuItem link_usuarios;
    // End of variables declaration//GEN-END:variables
}
